/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `schema_migrations`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `schema_migrations` (
  `version` varchar(255) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `t_core_domains`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_core_domains` (
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'Domain uuid. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_json` json DEFAULT NULL COMMENT 'Domain metadata',
  `c_ts_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: domain created',
  `c_ts_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp: domain modified',
  `c_stor_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci GENERATED ALWAYS AS (json_unquote(json_extract(`c_json`,_utf8mb4'$.name'))) VIRTUAL NOT NULL COMMENT '[VIRTUAL] Stor name',
  PRIMARY KEY (`c_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Domains definition table.';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `t_core_domains_map`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_core_domains_map` (
  `c_resource` binary(16) NOT NULL COMMENT 'Resource uuid',
  `c_core_user` binary(16) NOT NULL COMMENT 'User uuid (t_core_users.uuid)',
  `c_core_domain` binary(16) NOT NULL COMMENT 'Domain/tenant uuid (t_core_domains.uuid)',
  `c_ts_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: account created',
  `c_ts_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp: account modified'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Glued puts resources first. This table is to be joined with almost all requests.';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `t_core_users`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_core_users` (
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'User uuid (v4), generated by the identity server. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_profile` json DEFAULT NULL COMMENT 'User profile',
  `c_account` json DEFAULT NULL COMMENT 'Account settings',
  `c_attr` json DEFAULT NULL COMMENT 'Account attributes and state (enabled/disabled, GDPR anonymised, etc.)',
  `c_locale` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci GENERATED ALWAYS AS (json_unquote(json_extract(`c_account`,_utf8mb4'$.locale'))) VIRTUAL NOT NULL COMMENT 'Preferred locale',
  `c_nick` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Nickname',
  `c_ts_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: account created',
  `c_ts_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp: account modified',
  `c_stor_name` varchar(255) GENERATED ALWAYS AS (`c_nick`) VIRTUAL COMMENT '[VIRTUAL] Stor name',
  `c_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'Primary email',
  PRIMARY KEY (`c_uuid`),
  KEY `c_nick` (`c_nick`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Users profile, account settings, attriebutes, and default data.';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `t_skeleton_playground`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_skeleton_playground` (
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'User uuid (v4), generated by the identity server. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Playground title',
  `c_data` json DEFAULT NULL COMMENT 'Playground JSON',
  `c_ts_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: account created',
  `c_ts_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp: account modified',
  `c_stor_name` varchar(255) GENERATED ALWAYS AS (`c_title`) VIRTUAL COMMENT '[VIRTUAL] Stor name',
  PRIMARY KEY (`c_uuid`),
  KEY `c_title` (`c_title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='A sql playground in the skeleton service.';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `t_stor_links`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_stor_links` (
  `c_uid` int NOT NULL AUTO_INCREMENT COMMENT 'Link uuid',
  `c_core_user` int NOT NULL DEFAULT '1' COMMENT 'User who created a new link (by uploading a new or existing db object to a specific location under a user-friendly name .. see c_filename)',
  `c_filename` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'User firendly file-name of the soft/hardlink.',
  `c_inherit_table` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Authorization to be inherited according to table:object pair.',
  `c_inherit_object` int DEFAULT NULL COMMENT 'Authorization to be inherited according to table:object pair.',
  `c_ts_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp (link created).',
  `c_sha512` char(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL COMMENT 'Assigns a link to a specific object (row in t_stor_objects).',
  PRIMARY KEY (`c_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Content aware storage links table. All files in t_stor_objects are unique, t_stor_links provides soft/hard links (depending on stor''s configuration) to appropriate locations with a user-friendly name.';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `t_stor_objects`
--

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_stor_objects` (
  `c_json` json NOT NULL COMMENT 'Files metadata.',
  `c_sha512` char(128) GENERATED ALWAYS AS (json_unquote(json_extract(`c_json`,_utf8mb3'$.data.sha512'))) VIRTUAL NOT NULL,
  UNIQUE KEY `c_sha512` (`c_sha512`(6))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Content aware storage objects table. An object is a file with a unique sha512 hash (see the c_sha512 generated from c_json).';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping routines for database 'glued'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed

--
-- Dbmate schema migrations
--

LOCK TABLES `schema_migrations` WRITE;
INSERT INTO `schema_migrations` (version) VALUES
  ('20210823131601'),
  ('20210823131602'),
  ('20210823131603');
UNLOCK TABLES;
