-- migrate:up

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_core_domains` (
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'Domain uuid, generated by the identity server. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_core_user` binary(16) NOT NULL COMMENT 'Domain primary owner',
  `c_json` json DEFAULT NULL COMMENT 'User profile',
  `c_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Domain name',
  `c_nick` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Nickname',
  `c_ts_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: account created',
  `c_ts_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp: account modified',
  `c_stor_name` varchar(255) GENERATED ALWAYS AS (`c_name`) VIRTUAL COMMENT '[VIRTUAL] Stor name',
  PRIMARY KEY (`c_uuid`),
  KEY `c_name` (`c_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Domains definition table.';
/*!40101 SET character_set_client = @saved_cs_client */;

-- migrate:down

DROP TABLE `t_core_domains`