-- migrate:up

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `t_core_users` (
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'User uuid (v4), generated by the identity server. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_profile` json DEFAULT NULL COMMENT 'User profile',
  `c_account` json DEFAULT NULL COMMENT 'Account settings',
  `c_attr` json DEFAULT NULL COMMENT 'Account attributes and state (enabled/disabled, GDPR anonymised, etc.)',
  `c_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Primary email',
  `c_locale` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'en_US' COMMENT 'Preferred locale',
  `c_nick` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'Nickname',
  `c_ts_created` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: account created',
  `c_ts_modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp: account modified',
  `c_stor_name` varchar(255) GENERATED ALWAYS AS (BIN_TO_UUID(`c_uuid`)) VIRTUAL COMMENT '[VIRTUAL] Stor name',
  PRIMARY KEY (`c_uuid`),
  KEY `c_nick` (`c_nick`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Users profile, account settings, attriebutes, and default data.';
/*!40101 SET character_set_client = @saved_cs_client */;

-- migrate:down

DROP TABLE `t_core_users`