---
routes:

    #########################################################
    # CORE / NODES                                          #
    #########################################################

    fe_core_root:
        pattern:    /
        path:       /
        label:      Home
        dscr:       Root ingress point for glued, provides UI.
        service:    core
        methods:
            get:    Glued\Controllers\FeController:render_ui
    be_core:
        service:    core
        pattern:    /api/core
        path:       /api/core
        label:      Core
        dscr:       A routegroup, no methods here.

    #########################################################
    # API HOME                                              #
    #########################################################

    be:
        service:    core
        pattern:    /api
        path:       /api
        label:      API Home
        dscr:       Welcome route.
        methods:
            get:    Glued\Controllers\ServiceController:home

    #########################################################
    # CORE / STATUS                                         #
    #########################################################
    
    be_core_status_phpconst_v1:
        pattern:    ${routes.be_core.path}/status/phpconst/v1
        path:       ${routes.be_core.path}/status/phpconst/v1
        label:      Phpconst()
        dscr:       Returns phpconst().
        methods:
            get:    Glued\Controllers\StatusController:phpconst
    be_core_status_jwt_fetch_v1:
        pattern:    ${routes.be_core.path}/status/jwt/fetch/v1
        path:       ${routes.be_core.path}/status/jwt/fetch/v1
        label:      Show JWT
        dscr:       Returns the (undecoded) JWT token provided by client.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:token_fetch
    be_core_status_jwt_decode_v1:
        pattern:    ${routes.be_core.path}/status/jwt/decode/v1
        path:       ${routes.be_core.path}/status/jwt/decode/v1
        label:      Decode JWT
        dscr:       Returns the decoded JWT token provided by client.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:token_decode
    be_core_status_auth_v1:
        pattern:    ${routes.be_core.path}/status/auth/v1
        path:       ${routes.be_core.path}/status/auth/v1
        label:      Authentication status
        dscr:       Returns the undecoded jwt, the decoded jwt and internally stored account data.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:auth
    be_core_status_request_v1:
        pattern:    ${routes.be_core.path}/status/request/v1
        path:       ${routes.be_core.path}/status/request/v1
        label:      Show request headers
        dscr:       Returns the client's request headers.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:reflect_request
    be_core_status_sysinfo_v1:
        pattern:    ${routes.be_core.path}/status/sysinfo/v1
        path:       ${routes.be_core.path}/status/sysinfo/v1
        label:      Sysinfo
        dscr:       Returns /proc information from the host.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:sysinfo
    be_core_status_config_v1:
        pattern:    ${routes.be_core.path}/status/config/v1
        path:       ${routes.be_core.path}/status/config/v1
        label:      Glued Config
        dscr:       Returns Glued configuration.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:config
    be_core_status_server_v1:
        pattern:    ${routes.be_core.path}/status/server/v1
        path:       ${routes.be_core.path}/status/server/v1
        label:      Glued Config
        dscr:       Returns Glued configuration.
        service:    core
        methods:
            get:    Glued\Controllers\StatusController:server
    #########################################################
    # CORE / AUTH                                           #
    #########################################################

    be_core_auth_test_pass_v1:
        pattern:    ${routes.be_core.path}/auth/test/pass/v1
        path:       ${routes.be_core.path}/auth/test/pass/v1
        label:      "Authorization test: Pass"
        dscr:       Always returns a 200 respnse code. Intended for testing the nginx auth_request_module.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:say_pass
    be_core_auth_test_fail_v1:
        pattern:    ${routes.be_core.path}/auth/test/fail/v1
        path:       ${routes.be_core.path}/auth/test/fail/v1
        label:      "Authorization test: Fail"
        dscr:       Always returns a 403 respnse code. Intended for testing the nginx auth_request_module.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:say_fail
    be_core_auth_enforce_v1:
        pattern:    ${routes.be_core.path}/auth/enforce/v1
        path:       ${routes.be_core.path}/auth/enforce/v1
        label:      Authorization enforcer
        dscr:       Authorizes user for the action (crud) on a resource (uri). Returns 200 or 403 as expected by the nginx auth_request_module.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:enforce
    be_core_auth_users_v1:
        pattern:    ${routes.be_core.path}/auth/users/v1
        path:       ${routes.be_core.path}/auth/users/v1
        label:      Manage users
        dscr:       Api endpoint for managing users.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:users_r1
            post:    Glued\Controllers\AuthController:users_c1
    be_core_auth_tokens_v1:
        pattern:    ${routes.be_core.path}/auth/tokens/v1
        path:       ${routes.be_core.path}/auth/tokens/v1
        label:      Manage tokens
        dscr:       Api endpoint for managing tokens.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:tokens_r1
            post:    Glued\Controllers\AuthController:tokens_c1
    be_core_auth_roles_v1:
        pattern:    ${routes.be_core.path}/auth/roles/v1
        path:       ${routes.be_core.path}/auth/roles/v1
        label:      Manage roles
        dscr:       Api endpoint for managing roles.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:roles_r1
            post:   Glued\Controllers\AuthController:roles_c1
    be_core_auth_domains_v1:
        pattern:    ${routes.be_core.path}/auth/domains/v1
        path:       ${routes.be_core.path}/auth/domains/v1
        label:      Manage domains
        dscr:       Api endpoint for managing domains.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:domains_r1
            post:   Glued\Controllers\AuthController:domains_c1
    internal_core_auth_enforce_v1:
        pattern:    /internal/auth/v1
        path:       /internal/auth/v1
        label:      Authorization enforcer
        dscr:       Internal route handled nginx (hits be_core_auth_enforce_v1). Route method is a stub that will invoke only when nginx is misconfigured.
        service:    core
        methods:
            get:    Glued\Controllers\AuthController:enforce

    #########################################################
    # CORE / HEALTH                                         #
    #########################################################

    be_core_health_v1:
        pattern:    ${routes.be_core.path}/health/v1
        path:       ${routes.be_core.path}/health/v1
        label:      Core health
        dscr:       A healthcheck endpoint for the microservice.
        service:    core
        provides:   health
        methods:
            get:    Glued\Controllers\ServiceController:health

    #########################################################
    # CORE / ROUTES                                         #
    #########################################################

    be_core_routes_v1:
        pattern:    ${routes.be_core.path}/routes/v1
        path:       ${routes.be_core.path}/routes/v1
        label:      Routes list
        dscr:       A route list endpoint for the microservice.
        service:    core
        provides:   routes_list
        methods:
            get:    Glued\Controllers\ServiceController:routes_list

    be_core_apidocs_v1:
        pattern:    ${routes.be_core.path}/v1/apidocs
        path:       ${routes.be_core.path}/v1/apidocs
        label:      Openapi yamls/jsons
        dscr:       List URIs with Openapi source files
        service:    core
        methods:
            get:    Glued\Controllers\ServiceController:apidocs